Update chaosengine-concepts.md (#8)
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,18 +1,35 @@
  
-name: LitmusGo-CI
+name: LitmusDocs-CI
 on:
-  push:
-    branches:
-      - master
+  pull_request:
+    types: [ opened, synchronize, reopened ]
 
 jobs:
   embedmd:
     runs-on: ubuntu-latest
     steps:
 
+      #Using the last commit id of pull request
+      - uses: octokit/request-action@v2.x
+        id: get_PR_commits
+        with:
+          route: GET /repos/:repo/pulls/:pull_number/commits
+          repo: ${{ github.repository }}
+          pull_number: ${{ github.event.issue.number }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: set commit to output
+        id: getcommit
+        run: | 
+           prsha=$(echo $response | jq '.[-1].sha'  | tr -d '"')
+           echo "::set-output name=sha::$prsha" 
+        env: 
+          response:  ${{ steps.get_PR_commits.outputs.data }}
+          
       - uses: actions/checkout@v2
         with:
-          ref: ${{steps.getcommit.outputs.sha}}
+          ref: ${{steps.getcommit.outputs.sha}}      
 
       - uses: actions/setup-go@v2
         with:
@@ -25,15 +42,19 @@ jobs:
           cd docs
           embedmd -w $(find *.md)
         continue-on-error: true  
-
-      - name: Commit files
+        
+      - name: embedmd check
         run: |
-          git config --local user.email "litmuschaosbot@github.com"
-          git config --local user.name "LitmusChaos"
-          git commit -s -m "Add embedmd changes" -a
-        continue-on-error: true
-
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          count=$(git diff | wc -l)
+          if [ "$count" -eq "0" ]
+          then
+            echo "embedmd check failed\nThese files need to run embedmd once:"
+            git diff
+            echo "Please follow the instructions to run embedmd:"
+            echo "cd docs\nembedmd -w $(find *.md)"
+            echo "For more info visit https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md"
+            exit 1
+          else
+            echo "Nothing to embed"
+          fi
+        shell: sh
